---
kind: pipeline
type: kubernetes
name: wip-cicd

steps:
  - name: build-push
    image: docker
    environment:
      USERNAME:
        from_secret: registry_username
      PASSWORD:
        from_secret: registry_password
      REGISTRY:
        from_secret: registry_address
      CA_CERT:
        from_secret: registry_ca_cert
    commands:
      - printf '%b\n' "$CA_CERT" >> "/etc/ssl/certs/ca-certificates.crt"
      - docker login -u $USERNAME -p $PASSWORD $REGISTRY

trigger:
  branch:
    - wip-cicd
  events:
    - push
    - rollback