---
kind: pipeline
type: kubernetes
name: wip-cicd-pipeline

steps:
  - name: hello-world
    image: alpine
    commands:
      - echo "Hello World"

trigger:
  branch:
    - wip-cicd
  events:
    - push
    - rollback

---
kind: policy
name: wip-cicd-policy

match:
  repo:
    - "eng-project-quiz"

node_selector:
  heavy: "true"