---
kind: pipeline
type: kubernetes
name: wip-cicd

steps:
  - name: build-push
    image: docker
    environment:
      USERNAME:
        from_secret: registry_username
      PASSWORD:
        from_secret: registry_password
      REGISTRY:
        from_secret: registry_address 
    commands:
      - docker login -u $USERNAME -p $PASSWORD $REGISTRY

trigger:
  branch:
    - wip-cicd
  events:
    - push
    - rollback