---
kind: pipeline
type: kubernetes
name: wip-cicd

steps:
  - name: build-push
    image: gcr.io/kaniko-project/executor:debug
    environment:
      USERNAME:
        from_secret: registry_username
      PASSWORD:
        from_secret: registry_password
      REGISTRY:
        from_secret: registry_address
      CA_CERT:
        from_secret: registry_ca_cert
    commands:
      - exit # temporary to speed up pipeline
      - printf '%b\n' "$CA_CERT" > "/kaniko/ssl/certs/additional-ca-cert-bundle.crt"
      
      - COMMIT=${DRONE_COMMIT_SHA:0:8}
      - RAW_BRANCH=${DRONE_BRANCH}
      - BRANCH=$(echo $RAW_BRANCH | sed 's/[^a-zA-Z0-9]/-/g')
      - TAG=$BRANCH-$COMMIT
      - FULL_IMAGE_NAME=$REGISTRY/quizapp:$TAG
        
      - AUTH=$(echo -n $USERNAME:$PASSWORD | base64)
      
      - |
        JSON="{ \"auths\": { \"$REGISTRY\": { \"auth\": \"$AUTH\" } } }"
      - echo $JSON > "/kaniko/.docker/config.json"

      - /kaniko/executor --destination="$FULL_IMAGE_NAME" --context="." --dockerfile="/deploy/Dockerfile.QuizApp" --cache="true" --cache-repo="$REGISTRY/quizapp/cache" --cache-copy-layers="true" --cache-run-layers="true"

  - name: clone-infrastructure
    image: alpine/git
    commands:
      - git clone https://github.com/Deeplerg/eng-project-quiz-infra
  
  - name: edit-kustomization
    image: registry.k8s.io/kustomize/kustomize:v5.0.0
    commands:
      - cd eng-project-quiz-infra/kustomization/wip-cicd
      
      - COMMIT=${DRONE_COMMIT_SHA:0:8}
      - RAW_BRANCH=${DRONE_BRANCH}
      - BRANCH=$(echo $RAW_BRANCH | sed 's/[^a-zA-Z0-9]/-/g')
      - TAG=$BRANCH-$COMMIT
      - FULL_IMAGE_NAME=$REGISTRY/quizapp:$TAG

      - kustomize edit set image quizapp-image-name=$FULL_IMAGE_NAME
    
  - name: push-infrastructure-changes
    image: alpine/git
    commands:
      - git checkout main
      - git config --global user.email "drone@ci"
      - git config --global user.name "drone"
      - git add .
      - git commit -am "Update image tags"
      - git push

    

trigger:
  branch:
    - wip-cicd
  events:
    - push
    - rollback