---
kind: pipeline
type: kubernetes
name: wip-cicd

steps:
  - name: hello-world
    image: alpine
    commands:
      - echo "Hello World"

trigger:
  branch:
    - wip-cicd
  events:
    - push
    - rollback