---
kind: pipeline
type: kubernetes
name: wip-cicd

steps:
  - name: hello-world
    image: alpine
    environment:
      USERNAME:
        from_secret: docker_username
    commands:
      - echo ${USERNAME:3:2}

trigger:
  branch:
    - wip-cicd
  events:
    - push
    - rollback
  
---
kind: secret
name: docker_username
get:
  path: drone-registry-user-password-secret
  name: user